### ISSUE TITLE
Where to get the file mfd2.0.dic

### ISSUE THREAD

**Issue by datahunter1205** [AidaRamezani/moral-source-tracing#1]
Hello,
i am experimenting with your code. I  could not figure out where I can get the file "mfd2.0.dic" . The file is used in lexicons.py . Can you please provide this file?

Best regards
Raki

**Comment by AidaRamezani** [comment]
Hi Raki,
You can find it here: https://osf.io/ezn37/
http://www.jeremyfrimer.com/uploads/2/1/2/7/21278832/summary.pdf

Best,
Aida

**Comment by datahunter1205** [comment]
Hi Aida,
thank you very much!

Best regards
Raki
