### ISSUE TITLE
Where to get the file valence_rating.csv ?

### ISSUE THREAD

**Issue by datahunter1205** [AidaRamezani/moral-source-tracing#2]
Hello,
I could not figure out where I can get the file " **valence_rating.csv** " . The file is used in **moral_models.py** . Can you please provide this file?

![image](https://user-images.githubusercontent.com/25187268/153972049-6d59c518-6ccf-440a-a6b6-ea717b1847a4.png)

Best regards
Raki

**Comment by AidaRamezani** [comment]
No problem :) Here is the data: http://crr.ugent.be/archives/1003
